# Generated by Django 4.2.1 on 2023-05-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diplomanumber',
            old_name='username',
            new_name='user',
        ),
    ]
