# Generated by Django 4.2.1 on 2023-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='diploma_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='password',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
